# Generated by Django 5.2.6 on 2025-09-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleImpuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('impuesto', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
            options={
                'verbose_name': 'Detalle de Impuesto',
                'verbose_name_plural': 'Detalles de Impuestos',
            },
        ),
    ]
