# Generated by Django 5.2.6 on 2025-09-04 02:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la compra')),
                ('total', models.DecimalField(decimal_places=2, default=0, help_text='Total de la compra', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre la compra')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del proveedor', max_length=150)),
                ('celular', models.BigIntegerField(blank=True, help_text='Número de celular del proveedor', null=True)),
                ('direccion', models.TextField(blank=True, help_text='Dirección física del proveedor')),
                ('email', models.EmailField(blank=True, help_text='Correo electrónico del proveedor', max_length=100)),
                ('activo', models.BooleanField(default=True, help_text='Si el proveedor está activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha de registro del proveedor')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(help_text='Cantidad comprada', validators=[django.core.validators.MinValueValidator(1)])),
                ('costo_producto', models.DecimalField(decimal_places=2, help_text='Costo unitario del producto', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='purchases.compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.producto')),
            ],
            options={
                'verbose_name': 'Detalle de Compra',
                'verbose_name_plural': 'Detalles de Compras',
            },
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(blank=True, help_text='Proveedor de la compra', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='purchases.proveedor'),
        ),
    ]
