# Generated by Django 5.2.6 on 2025-09-04 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.CharField(editable=False, help_text='ID único del empleado', max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre del empleado', max_length=100)),
                ('apellido', models.CharField(help_text='Apellido del empleado', max_length=100)),
                ('celular', models.BigIntegerField(help_text='Número de celular único del empleado', unique=True)),
                ('estado', models.BooleanField(default=True, help_text='Si el empleado está activo')),
                ('email', models.EmailField(blank=True, help_text='Correo electrónico del empleado', max_length=100)),
                ('fecha_ingreso', models.DateField(auto_now_add=True, help_text='Fecha de ingreso del empleado')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['nombre', 'apellido'],
            },
        ),
    ]
